"""Initial schema

Revision ID: d4e02e562314
Revises: 
Create Date: 2026-01-12 13:48:05.045074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4e02e562314'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('creator_user_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('share_url', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_message_id', sa.String(length=50), nullable=True),
    sa.CheckConstraint('created_at IS NOT NULL', name='groups_created_at_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_groups_last_synced', 'groups', ['last_synced_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('group_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('source_guid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('system', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_created_at', 'messages', ['created_at'], unique=False, postgresql_using='btree')
    op.create_index('idx_messages_group_created', 'messages', ['group_id', 'created_at'], unique=False)
    op.create_index('idx_messages_group_id', 'messages', ['group_id'], unique=False)
    op.create_index('idx_messages_user_id', 'messages', ['user_id'], unique=False)
    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('messages_fetched', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sync_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('placeholder', sa.String(length=10), nullable=True),
    sa.Column('charmap', sa.JSON(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_attachments_message_id', 'attachments', ['message_id'], unique=False)
    op.create_index('idx_attachments_type', 'attachments', ['type'], unique=False)
    op.create_table('mentions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('start_position', sa.Integer(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mentions_message_id', 'mentions', ['message_id'], unique=False)
    op.create_index('idx_mentions_user_id', 'mentions', ['user_id'], unique=False)
    op.create_table('message_favorites',
    sa.Column('message_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('message_id', 'user_id')
    )
    op.create_index('idx_message_favorites_message', 'message_favorites', ['message_id'], unique=False)
    op.create_index('idx_message_favorites_user_id', 'message_favorites', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_message_favorites_user_id', table_name='message_favorites')
    op.drop_index('idx_message_favorites_message', table_name='message_favorites')
    op.drop_table('message_favorites')
    op.drop_index('idx_mentions_user_id', table_name='mentions')
    op.drop_index('idx_mentions_message_id', table_name='mentions')
    op.drop_table('mentions')
    op.drop_index('idx_attachments_type', table_name='attachments')
    op.drop_index('idx_attachments_message_id', table_name='attachments')
    op.drop_table('attachments')
    op.drop_table('sync_logs')
    op.drop_index('idx_messages_user_id', table_name='messages')
    op.drop_index('idx_messages_group_id', table_name='messages')
    op.drop_index('idx_messages_group_created', table_name='messages')
    op.drop_index('idx_messages_created_at', table_name='messages', postgresql_using='btree')
    op.drop_table('messages')
    op.drop_table('users')
    op.drop_index('idx_groups_last_synced', table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
